FROM python:3.11

WORKDIR app

COPY pyproject.toml .
RUN mkdir service && touch service/__init__.py && touch README.md && apt-get update && \
        pip3 install poetry && \
        poetry install


ENV PYTHONPATH "${PYTHONPATH}:/app/service"

EXPOSE 5005
