"""07 added api token

Revision ID: 002f761f0afd
Revises: a6bc6ef2fbab
Create Date: 2026-06-24 10:55:12.637004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002f761f0afd'
down_revision = 'a6bc6ef2fbab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_token',
    sa.Column('name', sa.TEXT(), nullable=False, comment="Человекочитаемое название ключа, напр. 'Ключ сервиса мониторинга'"),
    sa.Column('key_prefix', sa.String(length=16), nullable=False, comment='Первые 12 символов ключа для быстрого поиска'),
    sa.Column('key_hash', sa.String(length=64), nullable=False, comment='SHA-256 хэш ключа'),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='False — ключ отозван, но запись остаётся для аудита'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания ключа'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Последнее успешное использование ключа'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Срок действия ключа. NULL — бессрочный'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_api_token_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_token')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_token_key_hash'))
    )
    op.create_index(op.f('ix_api_token_key_prefix'), 'api_token', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_token_user_id'), 'api_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_token_user_id'), table_name='api_token')
    op.drop_index(op.f('ix_api_token_key_prefix'), table_name='api_token')
    op.drop_table('api_token')
    # ### end Alembic commands ###
