"""added unique constraint for checksum in payload

Revision ID: 09558449b3cc
Revises: 002f761f0afd
Create Date: 2026-07-01 12:42:36.352383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09558449b3cc'
down_revision = '002f761f0afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_payload_checksum'), 'payload', ['checksum'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_payload_checksum'), 'payload', type_='unique')
    # ### end Alembic commands ###
