"""05 added title and description to monitor algos

Revision ID: 2da1cacad586
Revises: 44f124f8623d
Create Date: 2026-05-19 22:36:29.929397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da1cacad586'
down_revision = '44f124f8623d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_algorithm', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('monitoring_algorithm', sa.Column('name', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_algorithm', 'name')
    op.drop_column('monitoring_algorithm', 'description')
    # ### end Alembic commands ###
