"""03 added task run time interval progress

Revision ID: 3bc9a74b2272
Revises: 8123cf4751e8
Create Date: 2026-04-05 23:14:47.569158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc9a74b2272'
down_revision = '8123cf4751e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_run_time_interval_progress',
    sa.Column('task_run_id', sa.BIGINT(), nullable=False),
    sa.Column('right_bound_at', sa.DateTime(), nullable=False),
    sa.Column('left_bound_at', sa.DateTime(), nullable=True),
    sa.Column('collected_data_amount', sa.INTEGER(), nullable=False),
    sa.Column('saved_data_amount', sa.INTEGER(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_run.id'], name=op.f('fk_task_run_time_interval_progress_task_run_id_task_run')),
    sa.PrimaryKeyConstraint('task_run_id', 'right_bound_at', name=op.f('pk_task_run_time_interval_progress'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_run_time_interval_progress')
    # ### end Alembic commands ###
