"""04 added execution arguments to task group

Revision ID: 44f124f8623d
Revises: 3bc9a74b2272
Create Date: 2026-04-07 23:56:28.221904

"""
import sqlalchemy as sa
from alembic import op

from service.adapters.outbound.repo.sa.base import JSONWithDatetime

# revision identifiers, used by Alembic.
revision = '44f124f8623d'
down_revision = '3bc9a74b2272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_group', sa.Column('execution_arguments', JSONWithDatetime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_group', 'execution_arguments')
    # ### end Alembic commands ###
