"""02 added task group, project, task group by project

Revision ID: 8123cf4751e8
Revises: e119f19af0ff
Create Date: 2026-04-04 12:29:55.423165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '8123cf4751e8'
down_revision = 'e119f19af0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    op.create_table('task_group',
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('queue_per_priority', sa.Boolean(), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_group'))
    )
    op.create_table('task_group_by_project',
    sa.Column('group_id', sa.BIGINT(), nullable=False),
    sa.Column('project_id', sa.BIGINT(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['task_group.id'], name=op.f('fk_task_group_by_project_group_id_task_group')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_task_group_by_project_project_id_project')),
    sa.PrimaryKeyConstraint('group_id', 'project_id', name=op.f('pk_task_group_by_project'))
    )
    # Добавляем колонку group_id как nullable сначала
    op.add_column('task', sa.Column('group_id', sa.INTEGER(), nullable=True))

    # Получаем уникальные имена групп из существующих задач
    connection = op.get_bind()

    # Шаг 1: SELECT DISTINCT group_name FROM task
    result = connection.execute(
        text("SELECT DISTINCT group_name FROM task WHERE group_name IS NOT NULL")
    )

    unique_group_names = [row[0] for row in result.fetchall()]

    # Шаг 2: Создаем записи в task_group для каждого уникального имени
    group_name_to_id = {}

    for group_name in unique_group_names:
        insert_result = connection.execute(
            text("""
                  INSERT INTO task_group (title, description, name, is_active, queue_per_priority)
                  VALUES (:title, :description, :name, :is_active, :queue_per_priority)
                  RETURNING id
              """),
            {
                'title': group_name,  # Используем имя группы как заголовок
                'description': f'Migrated group: {group_name}',
                'name': group_name,
                'is_active': True,
                'queue_per_priority': True
            }
        )
        group_id = insert_result.fetchone()[0]
        group_name_to_id[group_name] = group_id

    # Шаг 3: Обновляем group_id в task, сопоставляя task.group_name с task_group.name
    for group_name, group_id in group_name_to_id.items():
        connection.execute(
            text("UPDATE task SET group_id = :group_id WHERE group_name = :group_name"),
            {'group_id': group_id, 'group_name': group_name}
        )

    # Теперь делаем колонку group_id NOT NULL
    op.alter_column('task', 'group_id', nullable=False)

    op.create_foreign_key(op.f('fk_task_group_id_task_group'), 'task', 'task_group', ['group_id'], ['id'])
    op.drop_column('task', 'group_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('group_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_task_group_id_task_group'), 'task', type_='foreignkey')
    op.drop_column('task', 'group_id')
    op.drop_table('task_group_by_project')
    op.drop_table('task_group')
    op.drop_table('project')
    # ### end Alembic commands ###
