"""06 added time interval fields to task group model

Revision ID: a6bc6ef2fbab
Revises: 3208cb911918
Create Date: 2026-05-30 17:26:53.583152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6bc6ef2fbab'
down_revision = '3208cb911918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_group', sa.Column('time_interval_max_period', sa.FLOAT(), nullable=True))
    op.add_column('task_group', sa.Column('time_interval_first_left_bound_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_group', sa.Column('time_interval_first_left_bound_depth', sa.FLOAT(), server_default='86400', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_group', 'time_interval_first_left_bound_depth')
    op.drop_column('task_group', 'time_interval_first_left_bound_at')
    op.drop_column('task_group', 'time_interval_max_period')
    # ### end Alembic commands ###
