"""01 init

Revision ID: d60b90481319
Revises: 
Create Date: 2026-03-31 22:12:08.819142

"""
from alembic import op
import sqlalchemy as sa

from service.adapters.outbound.repo.sa.base import JSONWithDatetime

# revision identifiers, used by Alembic.
revision = 'd60b90481319'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('username', name=op.f('uq_app_user_username'))
    )
    op.create_table('monitoring_algorithm',
    sa.Column('type', sa.Enum('PERIODIC', 'SINGLE', name='monitoringalgorithmtype'), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitoring_algorithm'))
    )
    op.create_table('payload',
    sa.Column('data', JSONWithDatetime(), nullable=False),
    sa.Column('checksum', sa.UUID(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payload'))
    )
    op.create_table('periodic_monitoring_algorithm',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timeout', sa.FLOAT(), nullable=False),
    sa.Column('timeout_noize', sa.FLOAT(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['monitoring_algorithm.id'], name=op.f('fk_periodic_monitoring_algorithm_id_monitoring_algorithm')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_periodic_monitoring_algorithm'))
    )
    op.create_table('single_monitoring_algorithm',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timeouts', sa.JSON(), nullable=False),
    sa.Column('timeout_noize', sa.FLOAT(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['monitoring_algorithm.id'], name=op.f('fk_single_monitoring_algorithm_id_monitoring_algorithm')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_single_monitoring_algorithm'))
    )
    op.create_table('task',
    sa.Column('group_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('priority', sa.Enum('LOWEST', 'LOW', 'MEDIUM', 'HIGH', 'HIGHEST', name='prioritytype'), nullable=False),
    sa.Column('type', sa.Enum('UNDEFINED', 'TIME_INTERVAL', 'PAGINATION', name='tasktype'), nullable=False),
    sa.Column('monitoring_algorithm_id', sa.INTEGER(), nullable=False),
    sa.Column('execution_arguments', JSONWithDatetime(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'EXECUTION', 'SUCCEED', 'FINISHED', 'CANCELLED', 'ERROR', name='taskstatus'), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=False),
    sa.Column('payload_id', sa.BIGINT(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitoring_algorithm_id'], ['monitoring_algorithm.id'], name=op.f('fk_task_monitoring_algorithm_id_monitoring_algorithm')),
    sa.ForeignKeyConstraint(['payload_id'], ['payload.id'], name=op.f('fk_task_payload_id_payload')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    op.create_table('task_run',
    sa.Column('task_id', sa.BIGINT(), nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('priority', sa.Enum('LOWEST', 'LOW', 'MEDIUM', 'HIGH', 'HIGHEST', name='prioritytype'), nullable=False),
    sa.Column('type', sa.Enum('UNDEFINED', 'TIME_INTERVAL', 'PAGINATION', name='tasktype'), nullable=False),
    sa.Column('execution_arguments', JSONWithDatetime(), nullable=True),
    sa.Column('execution_bounds', JSONWithDatetime(), nullable=True),
    sa.Column('payload', JSONWithDatetime(), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'QUEUED', 'EXECUTION', 'INTERRUPTED', 'TEMP_ERROR', 'CANCELLED', 'ERROR', 'SUCCEED', name='taskrunstatus'), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_task_run_task_id_task')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_run'))
    )
    op.create_table('task_status_log',
    sa.Column('task_id', sa.BIGINT(), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'EXECUTION', 'SUCCEED', 'FINISHED', 'CANCELLED', 'ERROR', name='taskstatus'), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_task_status_log_task_id_task')),
    sa.PrimaryKeyConstraint('task_id', 'status_updated_at', name=op.f('pk_task_status_log'))
    )
    op.create_table('time_interval_task_progress',
    sa.Column('task_id', sa.BIGINT(), nullable=False),
    sa.Column('right_bound_at', sa.DateTime(), nullable=False),
    sa.Column('left_bound_at', sa.DateTime(), nullable=True),
    sa.Column('collected_data_amount', sa.INTEGER(), nullable=False),
    sa.Column('saved_data_amount', sa.INTEGER(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_time_interval_task_progress_task_id_task')),
    sa.PrimaryKeyConstraint('task_id', 'right_bound_at', name=op.f('pk_time_interval_task_progress'))
    )
    op.create_table('task_run_status_log',
    sa.Column('task_run_id', sa.BIGINT(), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'QUEUED', 'EXECUTION', 'INTERRUPTED', 'TEMP_ERROR', 'CANCELLED', 'ERROR', 'SUCCEED', name='taskrunstatus'), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_run.id'], name=op.f('fk_task_run_status_log_task_run_id_task_run')),
    sa.PrimaryKeyConstraint('task_run_id', 'status_updated_at', name=op.f('pk_task_run_status_log'))
    )
    op.create_table('task_run_time_interval_execution_bounds',
    sa.Column('task_run_id', sa.BIGINT(), nullable=False),
    sa.Column('task_id', sa.BIGINT(), nullable=False),
    sa.Column('right_bound_at', sa.DateTime(), nullable=False),
    sa.Column('left_bound_at', sa.DateTime(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_task_run_time_interval_execution_bounds_task_id_task')),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_run.id'], name=op.f('fk_task_run_time_interval_execution_bounds_task_run_id_task_run')),
    sa.PrimaryKeyConstraint('task_run_id', name=op.f('pk_task_run_time_interval_execution_bounds'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_run_time_interval_execution_bounds')
    op.drop_table('task_run_status_log')
    op.drop_table('time_interval_task_progress')
    op.drop_table('task_status_log')
    op.drop_table('task_run')
    op.drop_table('task')
    op.drop_table('single_monitoring_algorithm')
    op.drop_table('periodic_monitoring_algorithm')
    op.drop_table('payload')
    op.drop_table('monitoring_algorithm')
    op.drop_table('app_user')
    # ### end Alembic commands ###
